### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied

### ISSUE THREAD

**Issue by Tianqi-Ma** [AsaHIXx/CTCT#1]
Dear CTCT team,

Very impressive work you guys have done. And I'm playing around with your model using my own data. But an error occured like this:

```
[root@bc2c69566d6a CTCT]$! python ctc_inductive_prediction.py -i /storage/projects/internal/2023/CTCtracer/logtpm_file.csv -m pretrained_model/Tumor_Blood_binary_classifier.pth -c 2 -t data_examples/tumor_blood_label_ident.txt
./val_result/2023_02_27_05_00/ make success!!
Traceback (most recent call last):
  File "ctc_inductive_prediction.py", line 144, in <module>
    conf, pred, max_conf = pred_process(X, model, config)
  File "ctc_inductive_prediction.py", line 50, in pred_process
    _, neck, outputs, prob_labels, _, _, _ = model(exps)
  File "/usr/local/python/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/storage/baseDir/sourceDir/CTCT/model/ctc_model.py", line 82, in forward
    feat = self.features(x)
  File "/usr/local/python/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/storage/baseDir/sourceDir/CTCT/model/ctc_model.py", line 68, in forward
    extrac_f = self.feature_layers(x)
  File "/usr/local/python/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/python/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/python/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/python/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x20452 and 18856x1024)
```

The input file was processed using your script and looks like this:

```
> expr <- read.csv('logtpm_file.csv')
> dim(expr)
[1] 20452  2891
> expr[1:5,1:5]
             gene AAACCCAAGTCTCGTA.1 AAACCCACATATCGGT.1 AAACCCAGTGCTAGCC.1
1 ENSG00000121410                  0           368.5862                  0
2 ENSG00000268895                  0             0.0000                  0
3 ENSG00000148584                  0             0.0000                  0
4 ENSG00000175899                  0             0.0000                  0
5 ENSG00000245105                  0             0.0000                  0
  AAACGAAAGATAACAC.1
1                  0
2                  0
3                  0
4                  0
5                  0

```

I'm new to this area and have no idea what's going on. Could you please help with this?

**Comment by AsaHIXx** [comment]
Thank you for your feedback. I think the problem may lie in the inconsistency of gene numbers. We used 18856 genes in this study, but your csv contains 20452 genes. You can find the genes in 'data_examples/gene_ensemble_18856.txt'.  I hope this helps.

**Comment by Tianqi-Ma** [comment]
> Thank you for your feedback. I think the problem may lie in the inconsistency of gene numbers. We used 18856 genes in this study, but your csv contains 20452 genes. You can find the genes in 'data_examples/gene_ensemble_18856.txt'. I hope this helps.

Thanks for your immediate response. And I followed your advice to subset my input file like this
```
> ids <- read.table('data_examples/gene_ensemble_18856.txt')
> ids[1:5,]
[1] "ENSG00000000003" "ENSG00000000005" "ENSG00000000419" "ENSG00000000457"
[5] "ENSG00000000460"
> expr <- read.csv('/storage/projects/internal/2023/CTCtracer/logtpm_file.csv')
> table(expr[,1] %in% ids[,])

FALSE  TRUE
 3134 17318
> expr_sub <- expr[expr[,1] %in% ids[,],]
> dim(expr)
[1] 20452  2891
> dim(expr_sub)
[1] 17318  2891
> write.csv(expr_sub, file = "/storage/projects/internal/2023/CTCtracer/expr_matrix_sub.csv", quote=F, col.names=T, row.names=F, sep=',')
```
Howeve, this error still showed up:
```
[root@bc2c69566d6a CTCT]$! python ctc_inductive_prediction.py -i /storage/projects/internal/2023/CTCtracer/expr_matrix_sub.csv \
-m pretrained_model/Tumor_Blood_binary_classifier.pth -c 2 -t data_examples/tumor_blood_label_ident.txt
./val_result/2023_02_27_06_49/ make success!!
Traceback (most recent call last):
  File "ctc_inductive_prediction.py", line 144, in <module>
    conf, pred, max_conf = pred_process(X, model, config)
  File "ctc_inductive_prediction.py", line 50, in pred_process
    _, neck, outputs, prob_labels, _, _, _ = model(exps)
  File "/usr/local/python/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/storage/baseDir/sourceDir/CTCT/model/ctc_model.py", line 82, in forward
    feat = self.features(x)
  File "/usr/local/python/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/storage/baseDir/sourceDir/CTCT/model/ctc_model.py", line 68, in forward
    extrac_f = self.feature_layers(x)
  File "/usr/local/python/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/python/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/python/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/python/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x17318 and 18856x1024)
```
Does the input file have to cotain all the 18856 genes listed in the "gene_ensemble_18856.txt" file?

**Comment by AsaHIXx** [comment]
'Does the input file have to cotain all the 18856 genes listed in the "gene_ensemble_18856.txt" file?' Yes. If any gene in "gene_ensemble_18856.txt" is not involved in your file, you can set these genes' UMI counts to zero.  In addition, the order of the genes should be ensured to be consistent with the order of the genes in the "gene_ensemble_18856.txt" file. Hope this helps. :)

**Comment by Tianqi-Ma** [comment]
> 'Does the input file have to cotain all the 18856 genes listed in the "gene_ensemble_18856.txt" file?' Yes. If any gene in "gene_ensemble_18856.txt" is not involved in your file, you can set these genes' UMI counts to zero. In addition, the order of the genes should be ensured to be consistent with the order of the genes in the "gene_ensemble_18856.txt" file. Hope this helps. :)

Problem solved. Indeed, the error came from the inconsistency of genes. The genes in input file need to be exactly the same with provided gene list (either order or number). Thanks for your help.

And one more little question, is the logtpm transformation supposed to be done before or after the gene processing (subset/reorder and so on)? I prefer do transformation after the gene processing and this makes more sense to me.

**Comment by AsaHIXx** [comment]
> is the logtpm transformation supposed to be done before or after the gene processing (subset/reorder and so on)?

I think that the decision of which path to take may have minimal or negligible impact on the final result. In this study, we do transformation before the gene processing (subset/reorder ). Because the data we collected were sourced from various studies. Hope this helps.
